# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm install -g typescript --save-dev
          npm install
          npm run vscode:prepublish
        displayName: 'npm install, run prepublish'
      - script: |
          npm test --silent
          npm run coverage:upload
        displayName: 'Run tests and coverage'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: true
      - script: |
          npm run vscode:prepublish
        displayName: 'npm install, run prepublish'
      - script: |
          npm test --silent
        displayName: 'Run tests'
      - script: |
          npm run coverage:upload
        displayName: 'Run code coverage'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: true
      - script: |
          npm run vscode:prepublish
        displayName: 'npm install, run prepublish'
      - script: |
          npm test --silent
        displayName: 'Run tests'
      - script: |
          npm run coverage:upload
        displayName: 'Run code coverage'
